---
title: "Lab8"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data on Ames Livability
```{r}
towns <- read.csv("towns2.csv")
dim(towns)
str(towns)
head(towns)
towns$ames <- 0
towns$ames[52] <- 1
```

## Exercise 1
```{r}
library(ggplot2)
library(reshape2)

towns.melt <- melt(towns, id.vars = c(1:3, 14), measure.vars = 4:13)
qplot(value, Score, data = towns.melt, geom = "point") +
  facet_wrap(~ variable) +
  labs(x = NULL)
cor(towns$Score, towns[, 4:13])
```

## Exercise 2
```{r}
library(GGally)
ggpairs(towns[, 4:14], upper = list(continuous = wrap("cor", size = 2)),
        lower = list(continuous = wrap("points", stroke = 0, size = .5)))
sapply(towns[, 3:13], sd)
qplot(variable, value, data = towns.melt, geom = "boxplot") +
  labs(x = NULL, y = NULL)
```

## Exercise 3
```{r}
towns.pca <- prcomp(towns[, 3:13], scale. = T)  # include Population
summary(towns.pca)
round(towns.pca$rotation, 4)
qplot(1:11, towns.pca$sdev ^ 2, geom = c("point", "line"),
      xlab = "No. of PCs", ylab = "Component Variance (eigenvalue)", main = "Scree Plot")
```

## Exercise 4

## Exercise 5
```{r}
head(towns$City[order(towns$Score, decreasing = T)])
head(towns$City[order(towns.pca$x[, 1], decreasing = T)])
qplot(towns$Score, -towns.pca$x[, 1], col = as.factor(towns$ames), asp = 1) +
  labs(x = "Score", y = "negative PC1 score", color = "Ames")
cor(towns$Score, -towns.pca$x[, 1])
```
